package java.security.cert;
public class CertPathValidatorException
  extends java.security.GeneralSecurityException
{
public  CertPathValidatorException(java.lang.String msg, java.lang.Throwable cause, java.security.cert.CertPath certPath, int index) { throw new RuntimeException("Stub!"); }
public  CertPathValidatorException(java.lang.String msg, java.lang.Throwable cause) { throw new RuntimeException("Stub!"); }
public  CertPathValidatorException(java.lang.Throwable cause) { throw new RuntimeException("Stub!"); }
public  CertPathValidatorException(java.lang.String msg) { throw new RuntimeException("Stub!"); }
public  CertPathValidatorException() { throw new RuntimeException("Stub!"); }
public  java.security.cert.CertPath getCertPath() { throw new RuntimeException("Stub!"); }
public  int getIndex() { throw new RuntimeException("Stub!"); }
}
